# Generated by Django 3.2.5 on 2021-07-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('f_name', models.TextField()),
                ('l_name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.BigIntegerField()),
                ('addr', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('country', models.TextField()),
            ],
        ),
    ]
