# Generated by Django 3.2.5 on 2021-07-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donate',
        ),
    ]
