# Generated by Django 3.2.5 on 2021-07-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tsunami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave_height', models.FloatField()),
                ('date', models.DateField()),
                ('spread_area', models.FloatField()),
                ('country', models.TextField()),
                ('place', models.TextField()),
            ],
        ),
    ]
