# Generated by Django 3.2.5 on 2021-07-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Naturaldisaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='amt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
