# Generated by Django 3.2.5 on 2021-07-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volcano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mountain', models.TextField()),
                ('location', models.TextField()),
                ('year', models.IntegerField()),
                ('type', models.TextField()),
                ('subtype', models.TextField()),
                ('spread_area', models.FloatField()),
            ],
        ),
    ]
